### ISSUE TITLE
ccc

### ISSUE THREAD

**Issue by Roshin0320** [qmhc/grid-layout-plus#25]

**Comment by Roshin0320** [comment]
希望能完善auto-size属性，应该是设置为false之后就不能再被放置到超出父容器宽高的行或列

**Comment by mmclofe** [comment]
> 希望能完善auto-size属性，应该是设置为false之后就不能再被放置到超出父容器宽高的行或列

我现在的需求也是这样，希望只能在容器内部拖动，但现在元素可被纵向挤压出容器范围，这个问题你处理了吗？
